### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by micwoj92** [JarateKing/TF2-Hud-Reference#3]
Hello. Because one of contributors to your project(@JarateKing ) contributed to software that uses JarateKing License 3.0, your project also must use this license. Please help us or the gamerconfig team will sue you.

https://github.com/micwoj92/gamerconfig/blob/master/LICENSE

**Comment by micwoj92** [comment]
This applies to all projects, but I do not promote issue spamming. I expect you to fix this ASSAP!!

**Comment by JarateKing** [comment]
i have spoken to the author of the license and they gave me an exception because they are very cool, thanks

closing issue due to coolness

**Comment by micwoj92** [comment]
WOW! Thank you @JarateKing the author did message me too. I wish more support these days was so quick and good!
